# Тема 10. Декораторы и исключения
Отчет по Теме №10 выполнила:
- Санжанова Мария Олеговна
- ПИЭ-21-2

| Задание | Лаб_раб | Сам_раб     |
| ------ | ------ |-------------|
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа.
### Задание 1. 
Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из этого декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи.
P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.
### Результат 
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/1.png)

Этот код решает задачу вычисления числа Фибоначчи с использованием рекурсии и декоратора `@lru_cache` для оптимизации вычислений.
``` python
import time
from functools import lru_cache

@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)

if __name__ == '__main__':
    # Без декоратора
    start_time = time.time()
    result_without_cache = fibonacci(100)
    end_time = time.time()
    print(f"Без декоратора: {result_without_cache}, Время: {end_time - start_time} сек.")

    # С декоратором
    start_time = time.time()
    result_with_cache = fibonacci(100)
    end_time = time.time()
    print(f"С декоратором: {result_with_cache}, Время: {end_time - start_time} сек.")
```
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/1_1.png)
### Выводы 
Таким образом, время выполнения программы с использованием декоратора будет заметно меньше по сравнению с выполнением без него.


### Задание 2. 
Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130. Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.
### Результат 
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/2.png)
### Выводы 
Декоратор `check` добавляет проверку допустимости возраста перед вызовом функции `personal_info`. Если возраст находится в пределах от 0 до 100, он передается функции без изменений. В противном случае устанавливается строка 'Недопустимый возраст'. Тестовые вызовы функции `personal_info` демонстрируют, как декоратор влияет на передачу возраста. В последнем вызове `personal_info` в блоке `__main__` передаются четыре аргумента, но декоратор принимает только два. Это не вызовет ошибку, но все аргументы, начиная с третьего, будут проигнорированы.

### Задание 3. 
Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string.
Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.
### Результат 
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/3.png)
### Выводы 
Код пытается выполнить математическую операцию на каждом элементе списка. Если элемент списка не является числом, программа обрабатывает исключение и выводит сообщение об ошибке вместо результата операции. Блок `finally` гарантирует вывод сообщения "Вся информация обработана" независимо от наличия ошибок.

### Задание 4. 
Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводится “Успешная регистрация”
### Результат 
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/4.png)
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/4_1.png)
### Выводы 
Этот код представляет собой простую демонстрацию пользовательского исключения в Python. 
Код иллюстрирует использование пользовательского исключения для обработки конкретной ситуации, т.е. превышение длины строки.

### Задание 5. 
После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове
декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.
### Результат 
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/5.png)
### Выводы 
Класс `SiteChecker` действует как декоратор, добавляющий дополнительную функциональность вокруг функции `site`. 
Метод `__call__` выполняет проверку перед и после выполнения функции `site`.


## Самостоятельная работа. 
### Задание 1.
Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
### Результат
``` python
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Время выполнения: {end_time - start_time} с.")
        return result
    return wrapper

@timing_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end='\n')

if __name__ == '__main__':
    fibonacci()
```
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/6.png)
### Выводы
В этом коде создан декоратор `timing_decorator`, который измеряет время выполнения функции, обернутой этим декоратором. Затем, когда мы определяем функцию `fibonacci` и применяем к ней декоратор `@timing_decorator`, время выполнения будет выводиться после завершения функции.

### Задание 2.
Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.
### Результат
``` python
def read_file_content(file_name):
    try:
        with open(file_name, 'r') as file:
            content = file.read()
            if not content:
                raise Exception("Файл пустой")
            else:
                print("Информация из файла:", content)
    except Exception as e:
        print(e)

if __name__ == '__main__':
    # Содержимое пустого файла
    read_file_content('ПустойФайлПример.txt')

    # Содержимое файла с информацией
    read_file_content('НеПустойФайлПример.txt')
```
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/7.png)
### Выводы
Я создала два файла - один пустой и один с информацией, а затем написала программу для обработки ситуации с пустым файлом:
Были созданы два файла:
- `ПустойФайлПример.txt` (пустой файл)
- `НеПустойФайлПример.txt` (файл с информацией)
В этом коде функция `read_file_content` открывает файл с заданным именем, читает его содержимое, и если файл пустой, вызывает исключение. В `__main__` блоке мы используем эту функцию для обработки обоих файлов.

### Задание 3.
Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. 
### Результат
``` python
def add_two_and_input():
    try:
        user_input = input("Введите число: ")
        number = float(user_input)  # Пробуем преобразовать введенное значение в число
        result = 2 + number
        print("Результат сложения: ", result)
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

if __name__ == "__main__":
    # Тест с вводом числа
    add_two_and_input()

    # Тест с вводом строки
    add_two_and_input()
```
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/8.png)
### Выводы
Здесь используется `ValueError` для обработки ситуации, когда введенная строка не может быть преобразована в число. При вводе числа программа должна корректно сложить 2 и введенное число, а при вводе строки вывести сообщение об ошибке.

### Задание 4.
Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
### Результат
``` python
def custom_decorator(func):
    def wrapper(*args, **kwargs):
        print(f"Начало выполнения функции {func.__name__}")
        result = func(*args, **kwargs)
        print(f"Окончание выполнения функции {func.__name__}")
        return result
    return wrapper

@custom_decorator
def add_numbers(a, b):
    return a + b

@custom_decorator
def multiply_numbers(x, y):
    return x * y

if __name__ == "__main__":
    # Первая функция с декоратором
    result_add = add_numbers(39, 15)
    print("Результат сложения:", result_add)

    # Вторая функция с декоратором
    result_multiply = multiply_numbers(64, 6)
    print("Результат умножения:", result_multiply)
```
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/9.png)
### Выводы
В этом примере `custom_decorator` - это собственный декоратор, который выводит сообщение о начале и окончании выполнения функции. Функции `add_numbers` и `multiply_numbers` затем применяют этот декоратор с помощью `@custom_decorator`.
При запуске программы мы увидим сообщения до и после выполнения каждой функции, указывающие на начало и окончание их работы.

### Задание 5.
Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
### Результат
``` python
class NegativeNumberError(Exception):
    def __init__(self, message="Число не может быть отрицательным"):
        self.message = message
        super().__init__(self.message)

def process_positive_number(number):
    if number < 0:
        raise NegativeNumberError("Введено отрицательное число")
    else:
        print(f"Введенное положительное число: {number}")

if __name__ == "__main__":
    try:
        # Пример 1: ввод положительного числа
        positive_number = int(input())
        process_positive_number(positive_number)

        # Пример 2: ввод отрицательного числа
        negative_number = int(input())
        process_positive_number(negative_number)

    except NegativeNumberError as e:
        print(f"Ошибка: {e}")
```
![](https://github.com/smariasssss/SoftwareEngineering/blob/10be93f43dd0bfed9f0b8878d839567f1338803c/pics/10.png)
### Выводы
Мной было создано собственное исключение, которое будет возникать в случае, если введенное число меньше 0.
В этом примере создается собственное исключение `NegativeNumberError`, которое поднимается, если введенное число отрицательное. В блоке `__main__` мы приводим два примера: ввод положительного числа и ввод отрицательного числа. В случае отрицательного числа, будет вызвано исключение `NegativeNumberError`, и мы перехватываем его для вывода сообщения об ошибке.

## Общие выводы по теме.
Исключения - мощный механизм "защитного программирования", позволяющий сигнализировать о некорректном состоянии данных/системы и строить поведенческие цепочки на этом основании. Обработка исключений может строится как на стандартных типах, предоставляемых языком, так и на пользовательских типах исключений. В этом случае при обработке важно не потерять исходное исключение, дабы не нарушить флоу обработки.
Декоратор меняет поведение других функций. При этом он не прерывает работу основной функции. Декораторы в Python могут быть как функциями, так и классами. Обычно декораторы вызываются перед определением функции, которую нужно декорировать.
